# Utilizamos o try/except para apresentar uma excessão
# de uma maneira ,


try:
    resultado = 10/10
except:
    print("Ocorreu um erro na operação. Não é possível a divisão com denominador igual a zero" \
    "")
